version: '2.1'

services:
  mysql:
    container_name: pdg_mysql
    restart: always
    build: docker/images/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - pdg-data:/var/lib/mysql
    expose:
      - "3306"
    ports: 
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--execute=SHOW DATABASES;"]
      interval: 10s
      retries: 10

  phpmyadmin:
    container_name: pdg_phpmyadmin
    build: docker/images/phpmyadmin
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "6060:80"
    links:
      - mysql:db

  server:
    container_name: pdg_server
    build: pdg5-server
    expose:
      - "44555"
    ports:
      - "44555:44555"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  pdg-data:
