version: '2'
services:
  mysql:
    container_name: pdg_mysql
    restart: always
    build: images/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - pdg-data:/var/lib/mysql
    expose:
      - "3306"
    ports: 
      - "3306:3306"
  phpmyadmin:
    container_name: pdg_phpmyadmin
    build: images/phpmyadmin
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "6060:80"
    links:
      - mysql:db
volumes:
  pdg-data:
