package pdg5.server.persistent;

import javax.persistence.*;
import java.util.Date;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "pdg")
public class Message extends AbstractData implements java.io.Serializable {

	private Chat chat;
	private User user;
	private String content;
	private Date created;

	public Message() {
	}

	public Message(Chat chat, User user, String content, Date created) {
		this.chat = chat;
		this.user = user;
		this.content = content;
		this.created = created;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chat", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "content", nullable = false, length = 45)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}
	
	@Override
	public boolean equals(Object obj) {
		if(!(obj instanceof Message))
		{
			return false;
		}
			
		Message b = (Message) obj;
		
		return id == b.getId() &&
				chat.equals(b.getChat()) &&
				content.equals(b.getContent()) &&
				created.equals(b.getCreated()) &&
				user.equals(b.getUser());
	}
	
	@Override
	public String toString() {
		return id + ", " + chat + ", " +  content + ", " +  created + ", " + user;
	}

}
