package pdg5.server.persistent;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tournament generated by hbm2java
 */
@Entity
@Table(name = "tournament", catalog = "pdg")
public class Tournament implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date created;
	private Set chats = new HashSet(0);
	private Set matchlists = new HashSet(0);
	private Set games = new HashSet(0);

	public Tournament() {
	}

	public Tournament(String title, Date created) {
		this.title = title;
		this.created = created;
	}

	public Tournament(String title, Date created, Set chats, Set matchlists, Set games) {
		this.title = title;
		this.created = created;
		this.chats = chats;
		this.matchlists = matchlists;
		this.games = games;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tournament")
	public Set getChats() {
		return this.chats;
	}

	public void setChats(Set chats) {
		this.chats = chats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tournament")
	public Set getMatchlists() {
		return this.matchlists;
	}

	public void setMatchlists(Set matchlists) {
		this.matchlists = matchlists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tournament")
	public Set getGames() {
		return this.games;
	}

	public void setGames(Set games) {
		this.games = games;
	}
	
	@Override
	public boolean equals(Object obj) {
		if(!(obj instanceof Tournament))
		{
			return false;
		}
			
		Tournament b = (Tournament) obj;
		
		return id == b.getId() &&
				chats.equals(b.getChats()) &&
				((created == null && b.getCreated() == null ) || created.equals(b.getCreated())) &&
				games.equals(b.getGames()) &&
				matchlists.equals(b.getMatchlists()) &&
				((title == null && b.getTitle() == null ) || title.equals(b.getTitle()));
	}
	
	@Override
	public String toString() {
		return id + ", " + title + ", " + created;
	}

}
